config/routes.rb
Rails.application.routes.draw do
  get'/products', to: 'products#index'
  get'/products/new', to: 'products#new'

  post'/products', to: 'products#create'
  get'/products/:id', to: 'products#show', as: 'product' 
  get'/products/:id/edit', to: 'products#edit', as: 'edit_product' 
  patch'/products/:id', to: 'products#update'
  put'/products/:id', to: 'products#update'
  delete'/products/:id', to: 'products#delete'
  #resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
    @products=Product.all
    end
    def new
    @products=Product.new
    end
    def create
        @products=Product.new(product_params)
        if @products.save
            redirect_to products_path
        else
            render :new
        end
    end
    def edit
        @products=Product.find(params[:id])
    end 
    def update
        @products=Product.find(params[:id])
        if @products.update(product_params)
            redirect_to products_path
        else
            render :edit
        end
    end 
    def delete
        @products=Product.find(params[:id])
        @products.destroy
        redirect_to products_path
       
    end 
    private 
    def product_params
        params.require(:product).permit(:name, :description, :price)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<%= form_for  @products do |f| %>
<div>
    <%= f.label :name %>
    <%= f.text_field :name %>
</div>
<div>
    <%= f.label :descripction %>
    <%= f.text_area :description %>
</div>
<div>
    <%= f.label :price %>
    <%= f.number_field :price %>
</div>
<div>
    <%= f.submit %>
</div>
<% end %>

app/views/products/index.html.erb
<h1>Listado de productos</h1>
<%= link_to "Crear", products_new_path  %>
<table>
    <tr>
    
     <thead>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Precio</th>
     </thead>
     
    </tr>
    <tr>
     <% @products.each do |product| %>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td>
            
            <%= link_to "Editar", edit_product_path(product) %>
            <%= link_to "Eliminar",product, method: :delete, data:{confirm:"Deseas eliminar este articulo"} %>
        </td>
    </tr>
    
<% end %>

</table>

app/views/products/new.html.erb
<%= form_for  @products do |f| %>
<div>
    <%= f.label :name %>
    <%= f.text_field :name %>
</div>
<div>
    <%= f.label :descripction %>
    <%= f.text_area :description %>
</div>
<div>
    <%= f.label :price %>
    <%= f.number_field :price %>
</div>
<div>
    <%= f.submit %>
</div>
<% end %>